language: java
sudo: true # faster builds

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

script: "mvn cobertura:cobertura-integration-test"

after_success:
  - bash <(curl -s https://codecov.io/bash)